# Generated by Django 2.2.5 on 2019-10-11 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0019_auto_20191009_1045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('unit_price', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('banking_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.BankingDetail')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiries.Enquiry')),
                ('sale_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
