# Generated by Django 2.2.5 on 2019-10-11 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20191011_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
