# Generated by Django 2.2.5 on 2019-10-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20191012_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingdetail',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
