# Generated by Django 2.2.5 on 2019-10-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20191012_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='banking_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.BankingDetail'),
        ),
    ]
