# Generated by Django 2.2.5 on 2019-10-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20191012_0639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItems',
            new_name='LineItem',
        ),
    ]
