# Generated by Django 2.2.5 on 2019-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20191014_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='line_item_total',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
