# Generated by Django 2.2.5 on 2019-10-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_lineitem_line_item_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created']},
        ),
    ]
