# Generated by Django 2.2.5 on 2019-11-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20191016_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(default='quotation', max_length=255),
            preserve_default=False,
        ),
    ]
