# Generated by Django 2.2.5 on 2019-11-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiries.Enquiry'),
        ),
    ]
