# Generated by Django 2.2.5 on 2019-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191107_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinstallationassessement',
            name='type',
            field=models.CharField(choices=[('assements', 'Assements'), ('projects', 'Projects'), ('installations', 'Installations')], default='projects', max_length=255),
            preserve_default=False,
        ),
    ]
