# Generated by Django 2.2.5 on 2019-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectinstallationassessement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinstallationassessement',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
