# Generated by Django 2.2.5 on 2019-11-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectinstallationassessement_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinstallationassessement',
            name='company',
        ),
        migrations.AddField(
            model_name='projectinstallationassessement',
            name='client',
            field=models.CharField(default='CABS', max_length=255),
            preserve_default=False,
        ),
    ]
