# Generated by Django 2.2.5 on 2019-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191107_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinstallationassessement',
            name='type',
            field=models.CharField(choices=[('assement', 'Assement'), ('project', 'Project'), ('installation', 'Installation')], max_length=255),
        ),
    ]
