# Generated by Django 2.2.5 on 2019-11-04 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0022_auto_20191016_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultyLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('wip', 'Work In Progress'), ('closed', 'Closed')], default='open', max_length=255)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('faulty_decription', models.TextField()),
                ('faulty_close_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiries.Priority')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiries.Service')),
            ],
        ),
    ]
