# Generated by Django 2.2.5 on 2019-11-04 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faulty_logging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultylogging',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='faultylogging',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
