# Generated by Django 2.2.5 on 2020-01-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faulty_logging', '0006_auto_20191106_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
