# Generated by Django 2.2.5 on 2019-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('tech', 'Technician'), ('cs', 'Customer Services')], default='Admin', max_length=30),
        ),
    ]
