# Generated by Django 2.2.5 on 2019-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('tech', 'Technician'), ('cs', 'Customer Services')], default='admin', max_length=30),
        ),
    ]
