# Generated by Django 2.2.5 on 2019-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191001_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('tech', 'Technician'), ('sub-contractor', 'Sub-Contractor'), ('cs', 'Customer Services')], default='admin', max_length=30),
        ),
    ]
