# Generated by Django 2.2.5 on 2019-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorites'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FollowUps',
        ),
    ]
