# Generated by Django 2.2.5 on 2019-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_auto_20191003_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='next_follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
