# Generated by Django 2.2.5 on 2019-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_auto_20191003_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='attended_to',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('un-assigned', 'Un-Assigned')], default='un-assigned', max_length=255),
        ),
    ]
