# Generated by Django 2.2.5 on 2019-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_enquiry_attended_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='attended_to',
            field=models.CharField(choices=[('attended', 'Attended'), ('un-attended', 'Un-Attended')], default='un-attended', max_length=255),
        ),
    ]
