# Generated by Django 2.2.5 on 2019-10-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_auto_20191007_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
