# Generated by Django 2.2.5 on 2019-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_enquiry_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
