# Generated by Django 2.2.5 on 2019-10-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0012_auto_20191008_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('decription', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiries.Enquiry')),
            ],
        ),
    ]
