# Generated by Django 2.2.5 on 2019-10-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0013_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
