# Generated by Django 2.2.5 on 2019-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0014_auto_20191008_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
