# Generated by Django 2.2.5 on 2019-10-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0015_auto_20191008_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiries.Enquiry'),
        ),
    ]
