# Generated by Django 2.2.5 on 2019-10-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_auto_20191008_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
