# Generated by Django 2.2.5 on 2019-10-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0019_auto_20191009_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='next_follow_up_time',
        ),
    ]
