# Generated by Django 2.2.5 on 2019-10-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0020_remove_enquiry_next_follow_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('assement', 'Assement'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=255),
        ),
    ]
