# Generated by Django 2.2.5 on 2019-10-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0021_auto_20191016_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='assement_date',
            new_name='assessment_date',
        ),
    ]
