# Generated by Django 2.2.5 on 2019-11-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0022_auto_20191016_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='value',
        ),
    ]
