# Generated by Django 2.2.5 on 2019-11-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0023_remove_enquiry_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='assessment_date',
        ),
    ]
