# Generated by Django 2.2.5 on 2019-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0024_remove_enquiry_assessment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=255),
        ),
    ]
