# Generated by Django 2.2.5 on 2020-01-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0025_auto_20191112_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
