# Generated by Django 2.2.5 on 2020-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0026_auto_20200113_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
